apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-2
  labels:
    app: demo-api-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api-2
  template:
    metadata:
      labels:
        app: demo-api-2
    spec:
      containers:
        - name: demo-api-2
          image: solankiom/demo-api-2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-2
spec:
  selector:
    app: demo-api-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
      nodePort: 30090
  type: NodePort
